name: Python CI

on:
  push:
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Check Python
        run: python3 --version

      - name: Check app syntax
        run: python3 -m py_compile app.py

      - name: Run tests
        run: python3 -m unittest discover
